#!/bin/sh
USER_HOME=$(eval echo ~${SUDO_USER})
cp redshift-change /usr/local/bin/
echo 25000 > $USER_HOME/.local/redshift-temp
echo 0 >> $USER_HOME/.local/redshift-temp
chmod 777 $USER_HOME/.local/redshift-temp
sed -i "1s/^/redshift-change --disable\n/" $USER_HOME/.xinitrc
