#!/bin/sh

LOCAL=~/.local/redshift-temp

temp="$(head -n 1 $LOCAL)"
enabled="$(tail -n 1 $LOCAL)"

if [ "$1" = "--temp" ] ; then
	if [[ $enabled -eq 1 && $temp -lt "1000" ]] ; then
		echo "1000K"
	elif [[ $enabled -eq 1 && $temp -le "25000" ]] ; then
		echo "$temp"K
	fi
	exit 0
fi

if [ "$1" = "--toggle" ] ; then
	if [ $enabled -eq 0 ] ; then
		redshift -P -O $temp
		echo $temp > $LOCAL
		echo 1 >> $LOCAL
	else
		redshift -P -x
		echo $temp > $LOCAL
		echo 0 >> $LOCAL
	fi
	pkill -RTMIN+1 dwmblocks
	exit 0
fi

if [ "$1" = "--disable" ] ; then
	redshift -P -x
	sed -i '2s/1/0/' $LOCAL
	pkill -RTMIN+1 dwmblocks
	exit 0
fi


# Check $1 arg is a signed number
re='^[+-]?[0-9]+([.][0-9]+)?$'
if ! [[ $1 =~ $re ]] ; then
	echo "error: Not a number" >&2; exit 1
fi

let newtemp=$temp+$1


if [[ ($temp -gt "25000" && $newtemp -gt "25000") || $newtemp -lt "1000" ]] ; then
	echo $temp > $LOCAL
	echo 1 >> $LOCAL
else
	echo $newtemp > $LOCAL
	echo 1 >> $LOCAL
fi

if [[ $newtemp -gt "25000" ]] ; then
	redshift -P -x
	echo ""
elif [[ $newtemp -lt "1000" ]] ; then
	echo "" 
else
	redshift -P -O $newtemp
	echo "$newtemp"K
fi

pkill -RTMIN+1 dwmblocks
